# Generated by Django 2.2.4 on 2019-10-13 16:15

from django.db import migrations


def check_for_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.new_building = flat.construction_year >= 2015
        flat.save()

def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.new_building = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20191013_1758'),
    ]

    operations = [
        migrations.RunPython(check_for_new_building, move_backward),
    ]
