# Generated by Django 2.2.4 on 2019-10-13 20:06

from django.db import migrations
import phonenumbers


def parse_pure_phones(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        pure_phone = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        str_pure_phone = phonenumbers.format_number(pure_phone, phonenumbers.PhoneNumberFormat.E164)
        if phonenumbers.is_valid_number(pure_phone) and str_pure_phone.startswith('+7'):
            flat.owner_phone_pure = pure_phone
            flat.save()


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner_phone_pure = ''
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_phone_pure'),
    ]

    operations = [
        migrations.RunPython(parse_pure_phones, move_backward),
    ]
