# Generated by Django 2.2.4 on 2019-10-14 15:26

from django.db import migrations
import phonenumbers


def parse_owners_info_from_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            name=flat.owner, 
            phonenumber=flat.owners_phonenumber,
            defaults={
            'phone_pure': flat.owner_phone_pure,
            }
        )

def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Owner.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_owner'),
    ]

    operations = [
        migrations.RunPython(parse_owners_info_from_flats, move_backward),
    ]
