# Generated by Django 2.2.4 on 2019-10-14 17:38

from django.db import migrations


def add_flats_to_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner = Owner.objects.get_or_create(
            name=flat.owner,
            phonenumber=flat.owners_phonenumber,
            defaults={
                'phone_pure': flat.owner_phone_pure,
            }
        )[0]
        owner.flats.add(flat)
        owner.save()


def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        owner.flats.clear()
        owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20191014_1826'),
    ]

    operations = [
        migrations.RunPython(add_flats_to_owners, move_backward),
    ]
